name: Build and Test on Pull Request

on:
  pull_request:
    branches:
      - develop
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create a dummy .env file for testing
        run: |
          echo "JWT_SECRET=test_secret_key" >> .env
          echo "AWS_ACCESS_KEY_ID=test_access_key" >> .env
          echo "AWS_SECRET_ACCESS_KEY=test_secret" >> .env
          echo "AWS_REGION=us-east-1" >> .env
          echo "AWS_BUCKET_NAME=test_bucket" >> .env
          echo "FREE_PLAN_MAX_ACTIVE_CLIENT_CARDS=20" >> .env
          echo "FREE_PLAN_MAX_CARDS=1" >> .env
          echo "PORT=8080" >> .env
          # Add any other required variables here

      - name: Build Docker Image
        run: docker build . --tag my-api-test

      - name: Run Docker Container and Check for Startup Errors
        run: |
          docker run --rm --name my-api-test-container -p 8080:8080 --env-file .env my-api-test &
          sleep 5 # Give the container a few seconds to start
          if [ "$(docker inspect -f '{{.State.Running}}' my-api-test-container)" != "true" ]; then
            echo "Container failed to start."
            docker logs my-api-test-container
            exit 1
          fi
          echo "Container started successfully."
